# docker-compose.yml버전은 무엇으로 할것인가? portainer를 인식하는 최신버전이 3.7
version: "3.7"

# 단일컨테이너가 아니라 여러개의 컨테이너를 구동하고, 꺼졌을때 자동 재부팅 할 수있게 하기
# portainer에서 container만드는것과 같은 과정이다.
# stack 만들기
services:
  # portainer에서 만드는것과 같은 방식이다.
  nginx:
    # nginx라고 써도 되지만 이렇게 되면 매번 최신 버전을 불러오고 호환성 문제가 발생 할 수 있따.
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_5ban_network
    volumes:
      # container: host
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gis_5ban_static:/data/static/
      - gis_5ban_media:/data/media
      - gis_log:/var/log/nginx/

  goaccess:
    image: allinurl/goaccess:1.5.2
    volumes:
      - gis_log:/var/log/nginx/
    ports:
      - 7890:7890 # 외부포트 : 내부포트
    command: /var/log/nginx/gis_access.log -o /var/log/nginx/report.html --log-format=COMBINED --real-time-html
#    /var/log/nginx/gis_access.log 인풋
#    -o /var/log/nginx/report.html 아웃풋
#    --log 로그파일
#    --real 리얼타임 로그

  django:
    # run서버를 통해서 자신이 static을 구동만 하는것 gis_5ban_django:1
    # 서비스를 업데이트 할때마다 portainer에서 stack을 지우고 stack에서 dicker-compose.yml을 업로드하기만 하면된다. image 버전만 바꿔주면 된다.
    # 이전에는 끄면 계정 정보가 날아갔지만 gis_5ban_django:4부터는 mariadb가 있어서 서버를 껐다켜도 데이터가 남아있다.
    image: gis_5ban_django:5
    networks:
      - gis_5ban_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gis_5ban_static:/home/gis_5ban_1/staticfiles/
      - gis_5ban_static:/home/gis_5ban_1/media/
      - gis_log:/val/log/nginix/
#    # port설정
#    ports:
#      - 8080:8000
    # 민감정보 감추기 docker secret이용 경로는 /run/secrets/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_5ban_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    # 환경설정 순서는 상관 없다
    environment:
      # python -> gisweb_1 -> settigns -> deploy.py 에있는 DATABASE내용 정보 넣기
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD


# 선언해주기
networks:
  gis_5ban_network:

# gis_5ban_static을 만든다고 해서 portainer에서 만든걸 쓰는게 아니라
# 새로 gis_5ban_static, gis_5ban_media를 CMD로 만든거다.
volumes:
  gis_5ban_static:
  gis_5ban_media:
  gis_mariadb:
  gis_log:

# 선언하기.
# secret은 volumes와 다르게 portainer에서 만들었다. 우리만 작성하게 하는것
secrets:
  DJANGO_SECRET_KEY:
    # portainer에서 만든 것을 불러오겠다
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
